// Code generated by "mapstructure-to-hcl2 -type QemuConfig"; DO NOT EDIT.
package config

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatQemuConfig is an auto-generated flat version of QemuConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatQemuConfig struct {
	QemuBinarySourcePath      *string `mapstructure:"qemu_binary_source_path" required:"true" cty:"qemu_binary_source_path"`
	QemuBinaryDestinationPath *string `mapstructure:"qemu_binary_destination_path" cty:"qemu_binary_destination_path"`
}

// FlatMapstructure returns a new FlatQemuConfig.
// FlatQemuConfig is an auto-generated flat version of QemuConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*QemuConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatQemuConfig)
}

// HCL2Spec returns the hcl spec of a QemuConfig.
// This spec is used by HCL to read the fields of QemuConfig.
// The decoded values from this spec will then be applied to a FlatQemuConfig.
func (*FlatQemuConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"qemu_binary_source_path":      &hcldec.AttrSpec{Name: "qemu_binary_source_path", Type: cty.String, Required: false},
		"qemu_binary_destination_path": &hcldec.AttrSpec{Name: "qemu_binary_destination_path", Type: cty.String, Required: false},
	}
	return s
}
