name: Archlinuxarm armv8 docker
on:
  push:
    branches: [ master ]
  schedule:
    # once a week
    - cron:  '0 0 * * 1'
jobs:

  build:
    name: Push archlinuxarm-armv7 image to docker registry
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Setup backports
        run: sudo /bin/bash -c 'echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" >> /etc/apt/sources.list'

      - name: Fetch additional packages
        run: sudo apt-get update && sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar autoconf make

      - name: Install newer bsdtar manually
        run: |
          wget https://www.libarchive.org/downloads/libarchive-3.3.2.tar.gz
          tar xzf libarchive-3.3.2.tar.gz
          cd libarchive-3.3.2
          ./configure
          make
          sudo make install 

      - name: Build
        run: go build -v .

      - name: Fetch packer
        run: wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip && unzip -d . packer_1.7.2_linux_amd64.zip

      - name: Build image
        run: sudo ./packer build -var docker_user=$docker_user -var docker_password=$docker_password -var docker_repository=$docker_repository boards/armv8/archlinuxarm-docker.json
        env:
          docker_user: ${{ secrets.docker_user }}
          docker_password: ${{ secrets.docker_password }}
          docker_repository: mkaczanowski/archlinuxarm 
